# Polynomial Regression

* Non-lineear feauture relationships to label
* Interaction terms between feautures
* interaction term
* PolynomialFeatures which automatically creates both higher order feature polynomials and the interaction tersm betwwen all feature combinations

## Features include:
 * The bias (the value of 1.0)
 * Values raised the power for each degree(x^2,x^3)
 * Interactions between all pairs of features (x1*x2,x1*x3)
 
 
### Converting Two Features A and B
* 1.A,B,A^2,AB,B^2

### Generalized terms feautres X1 and X2
* 1,X1,X',X1^2,X1X2,X2^2

### Example if row was X1=2 and X2=3
* 1,2,3,4,6,9



Polynomial Regression does not require the relationship between the independent and dependent variables to be linear in the data set,This is also one of the main difference between the Linear and Polynomial Regression.Polynomial Regression is generally used when the points in the data are not captured by the Linear Regression Model and the Linear Regression fails in describing the best result clearly.


* 1.Lineer Regression --> y=b0+b1X1
* 2.Multiple Lineer Regression --> y=b0+b1X1+b2X2+bnXn
* 3.Polynomial Regression --> y=b0+b1x1+b2X1^2+bnX1^n

# Creating Polynomial Features

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X=df.drop("sales",axis=1)

In [5]:
y=df["sales"]

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter=PolynomialFeatures(degree=2,include_bias=False)

In [8]:
polynomial_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [9]:
polynomial_converter.transform(X)

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

In [10]:
polynomial_converter.transform(X).shape

(200, 9)

In [11]:
X.shape

(200, 3)

In [12]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

In [13]:
poly_features=polynomial_converter.transform(X)

In [14]:
poly_features.shape

(200, 9)

In [15]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

* 1- 230.1 
* 2-37.8 
* 3-69.2 
* 4-230.1*37.8 
* 5-230.1*69.2 
* 6-37.8*69.2 
* 7-230.1^2 
* 8-37.8^2 
* 9-69.2^2

In [16]:
polynomial_converter.fit_transform(X)

array([[ 230.1 ,   37.8 ,   69.2 , ..., 1428.84, 2615.76, 4788.64],
       [  44.5 ,   39.3 ,   45.1 , ..., 1544.49, 1772.43, 2034.01],
       [  17.2 ,   45.9 ,   69.3 , ..., 2106.81, 3180.87, 4802.49],
       ...,
       [ 177.  ,    9.3 ,    6.4 , ...,   86.49,   59.52,   40.96],
       [ 283.6 ,   42.  ,   66.2 , ..., 1764.  , 2780.4 , 4382.44],
       [ 232.1 ,    8.6 ,    8.7 , ...,   73.96,   74.82,   75.69]])

# Training and Evaluating Model

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(poly_features,y,test_size=0.3,random_state=101)

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model=LinearRegression()

In [21]:
model.fit(X_train,y_train)

LinearRegression()

In [22]:
test_predictions=model.predict(X_test)

In [23]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [24]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [25]:
MAE=mean_absolute_error(y_test,test_predictions)

In [26]:
MSE=mean_squared_error(y_test,test_predictions)

In [27]:
RMSE=np.sqrt(MSE)

In [28]:
MAE

0.4896798044803488

In [29]:
RMSE

0.6646431757268974

In [30]:
model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [31]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [32]:
X.iloc[0]

TV           230.1
radio         37.8
newspaper     69.2
Name: 0, dtype: float64

# Bias-Variance Trade-Off
## Overfitting versus UnderFitting

* underfitting(high bias)
* overfitting (high variance)

* Overfitting : Model fits too much to the noise from the data.This often results **low error on training sets but high error on test/validation sets**

- overfit on the training data ? --> Thats means we would perform porly on new test data
