* Bayes' Theorem is a probability formula that leverages previously known probabilities to define probability of related events occuring.

* ***P(A/B)= P(B/A).P(A) / P(B)***


* p(Ck|x) =p(Ck).p(x|Ck)/p(x)
* p(Ck|X)=p(Ck,x1,x2,..xn)/p(x)

 ## Feature Extraction From Text
* Most NLP libraries have a built-in list of common stop words.

* TF-IDF Vectorization

* Term frequency **tf(t,d)** : is the raw count of a term in a document:
    * The number of times that term **t** occurs in document **d**.


  
* TF-IDF = term frequency * (1/document frequency)
* TF-IDF = term frequency * inverse document freq




In [136]:
with open("One.txt") as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one=set(words_one)

In [137]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [138]:
with open("Two.txt") as mytext:
    words_two = mytext.read().lower().split()
    uni_words_two=set(words_two)

In [139]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [140]:
all_uni_words=set()
all_uni_words.update(uni_words_one)

In [141]:
all_uni_words.update(uni_words_two)

In [142]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [143]:
full_vocab=dict()
i=0

for word in all_uni_words:
    full_vocab[word]=i
    i+=1

In [144]:
full_vocab

{'dogs': 0,
 'about': 1,
 'catching': 2,
 'surfing': 3,
 'popular': 4,
 'pets': 5,
 'a': 6,
 'this': 7,
 'water': 8,
 'waves': 9,
 'is': 10,
 'animals': 11,
 'furry': 12,
 'story': 13,
 'fun': 14,
 'sport': 15,
 'our': 16,
 'canine': 17,
 'are': 18}

In [145]:
one_freq=[0]*len(full_vocab)
two_freq=[0]*len(full_vocab)
all_words=['']*len(full_vocab)

In [146]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [147]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [148]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [149]:
with open("One.txt") as f:
    one_text=f.read().lower().split()

In [150]:
for word in one_text:
    word_index=full_vocab[word]
    one_freq[word_index] +=1

In [151]:
one_freq

[2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1]

In [152]:
with open("Two.txt") as f:
    two_text=f.read().lower().split()

In [153]:
for word in two_text:
    word_index=full_vocab[word]
    two_freq[word_index] +=1

In [154]:
two_freq

[0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 3, 0, 0, 1, 1, 1, 0, 0, 0]

In [155]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [156]:
for word in full_vocab:
    word_index=full_vocab[word]
    all_words[word_index]=word

In [157]:
all_words

['dogs',
 'about',
 'catching',
 'surfing',
 'popular',
 'pets',
 'a',
 'this',
 'water',
 'waves',
 'is',
 'animals',
 'furry',
 'story',
 'fun',
 'sport',
 'our',
 'canine',
 'are']

In [158]:
import pandas as pd
bow=pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

In [159]:
bow

dogs  about  catching  surfing  popular  pets  a  this  water  waves  is  \
0     2      1         0        0        0     1  1     1      0      0   1   
1     0      1         1        2        1     0  1     1      1      1   3   

   animals  furry  story  fun  sport  our  canine  are  
0        1      1      1    0      0    1       1    1  
1        0      0      1    1      1    0       0    0

In [160]:
text=["This is a line",
      "This is another line",
      "Completely different line"]

In [161]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [162]:
cv=CountVectorizer(stop_words="english")

In [163]:
sparse_matrix=cv.fit_transform(text)

In [164]:
sparse_matrix.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])

In [165]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [166]:
tfidf=TfidfTransformer()

In [167]:
sparse_matrix

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [168]:
cv=CountVectorizer()

In [169]:
sparse_matrix=cv.fit_transform(text)

In [170]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [173]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [171]:
tfidf=TfidfTransformer()


In [172]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [174]:
results=tfidf.fit_transform(sparse_matrix) #BOW -->TF-IDF,bag of words

In [175]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [176]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [178]:
tv=TfidfVectorizer()

In [180]:
tv_results=tv.fit_transform(text)

In [181]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])